[package]
name = "gen-native"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rand = { version = "0.8" }

[build-dependencies]
csv = "1.3"
serde = { version = "1", features = ["derive"] }
