name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
     # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: oven-sh/setup-bun@v1

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Run warmup
      working-directory: warmup
      run: cargo run --release

    - name: Build gen-native
      working-directory: gen-native
      run: cargo build --release

    - name: Build gen-wasm
      working-directory: gen-wasm
      run: wasm-pack build --release --target web

    - name: Build demo
      working-directory: demo-wasm
      run: |
        bun install
        bun run build

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: demo-wasm/dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

